// <auto-generated />
using Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace TZstore.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200618135457_48485")]
    partial class _48485
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("Data.Models.OrderDO", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("OrderState")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("Ordertime")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasMaxLength(50);

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER")
                        .HasMaxLength(50);

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Data.Models.ProductDO", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("TEXT")
                        .HasMaxLength(300);

                    b.Property<int>("Inventory")
                        .HasColumnType("INTEGER")
                        .HasMaxLength(100);

                    b.Property<double>("Price")
                        .HasColumnType("REAL")
                        .HasMaxLength(100);

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<string>("ProductNumber")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<string>("ProductType")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<string>("ShowCarYN")
                        .HasColumnType("TEXT")
                        .HasMaxLength(300);

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Data.Models.UserDO", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT")
                        .HasMaxLength(300);

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("UserPassword")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
